# Snapshot of /opt/robot/share/planner/config/localplanner.yaml.
lookAheadDis: 1.5
maxSpeedX: 1.5
maxSpeedY: 0.6
maxTheta: 1.0
barking_deceleration: 1.0
stop_distance: 0.7
max_v_threshold: 1.2
robotLength: 0.84
robotWidth: 0.5
sensorOffsetX: 0
sensorOffsetY: 0
obstacleHeightThre: 0.10
goal_in_ob_dis: 0.25
goal_in_ob_z: 0.5
pointPerPathThre: 1
input_source: /NAV_POINTS
grid_size_: 0.05
grid_occu_num_: 2
enable_cloud_stacking: false
cloud_stack_size: 1
directLine_mode: true
judge_close: false
change_close: true
backward_mode: false
judge_turn: false
xy_tolerance: 0.1
yaw_tolerance: 0.1
block_number: 1
dwa_fine_tune_distance: 0.5
weight_goal: 1.0
weight_yaw: 0.5
weight_spdy: 0.2
weight_ob1: 0.6
weight_ob2: 0.8
weight_ob3: 1.0
local_point_dis: 3.0
local_point_dis_v_max: 5.0
local_try: true
path_num: 4641
path_sample_num: 10
grid_voxel_size: 0.05
grid_voxel_offset_x: -1.475
grid_voxel_offset_y: -1.975
grid_voxel_num_x: 90
grid_voxel_num_y: 80
turn_yaw_kp: 1.5
angleThreshold: 30.0
sumAngleThreshold: 75.0
minSegmentLength: 0.02
trackDis: 1.5
speed_ratio: 1.0
speed_ratio_yaw: 1.0
dl_min_yaw: 0.7
dl_min_x: 0.25
dl_min_y: 0.25
pl_min_yaw: 0.25
pl_min_x: 0.25
pl_min_y: 0.25
dl_line_yaw_min: 0.2
close_deceleration: 1.0
proximity_distance: 0.5
warning_threshold: 10.0
vel_acc_threshold: 1.0
x_acc_increment: 0.05
count_num: 10
only_rotate_yaw: 0.35
adjust_yaw_min_: 1
rotate_detect_dis: 0.0
turn_approach_threshold: 0.2
monitor_loop_frequency: 10.0
sharp_turn_angle: 60.0
